services:
  web:
    build:
      context: .
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    volumes:
      - ./app:/var/www/html # Mount app code
    environment:
      - CI_ENV=production

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci3db
      MYSQL_USER: ci3user
      MYSQL_PASSWORD: ci3pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./nigenius.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  mysql_data:
